### ISSUE TITLE
stingray' error

### ISSUE THREAD

**Issue by intekhab1025** [slott56/Stingray-Reader#5]
I am getting error module 'stingray' has no attribute 'cobol' while executing the same code in python 3.7

**Comment by slott56** [comment]
This is likely because the `PYTHONPATH` environment variable isn't being used to point to the package. If you download the repository, use `export PYTHONPATH=/path/to/the/repo/stingray` to point to the Python version of the library.
 
Or it's possible it's not installed at all. You can run `python setup.py install` to install the package and put it on your enviroment's path.

It's often helpful to use a virtual environment manager when installing new packages.

It helps to provide more information with the problem report: OS, Current Working directory, the `PYTHONPATH` environment variable, what you did to download and install, and what the *actual* error is.

**Comment by intekhab1025** [comment]
That worked, thank you very much :)
